### ISSUE TITLE
Can't read .cs and .dll mods

### ISSUE THREAD

**Issue by Craluminum2413** [GaslampStudios/VintageLauncher#2]
**Describe the bug**
By some reason it can't read a dozen of mods that come in form of single .cs or .dll file.
[Example of single .cs file:](https://mods.vintagestory.at/stepup)
[Example of single .dll file](https://mods.vintagestory.at/vshud):

**To Reproduce**
1. Put any .cs or .dll into mods folder
2. Start launcher
3. Open "Mods" tab
4. It constantly gives an error

**Expected behavior**
It loads them fine

**Screenshots**
![image](https://user-images.githubusercontent.com/69315569/224258088-613b8de2-659f-46c7-a6d8-4f222aa52b5e.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by GaslampStudios** [comment]
FIXED in dev.  Will be released in the next point release.

**Comment by GaslampStudios** [comment]
Deployed on 3/11
