### ISSUE TITLE
No longer launches game

### ISSUE THREAD

**Issue by LocoMinerDad** [GaslampStudios/VintageLauncher#6]
I updated the most recent version, and it said it was missing a lot of files and would not work. I uninstalled it to the previous version that worked. It comes up with no errors, but when I click launch, nothing happens. I tried the first version.  Same thing.

**Comment by GaslampStudios** [comment]
The preview version was written to only run for a few months. I had planned on getting a 1.0 release out a lot sooner, but at least it lit a fire under me!  

So this is not a bug -- it's as designed. 

DM me on Discord (#SimonKoi9968) or the mod page, and I'll help you get the new release sorted out.

**Comment by GaslampStudios** [comment]
Functioning as designed.
